version: '3.8'

services:
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: local
      context: .
      args:
        - PORT=${PORT}
        - AUTH_TOKEN=${AUTH_TOKEN}
        - REPOSITORY_URL=${REPOSITORY_URL}
        - REPOSITORY_URI=${REPOSITORY_URI}
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    environment:
      - TZ=${TZ}
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules/
  my-service-sonar:
    container_name: service_sonar
    env_file: .env
    build:
      target: test
      context: .
      args:
        - PORT=${PORT}
        - AUTH_TOKEN=${AUTH_TOKEN}
        - REPOSITORY_URL=${REPOSITORY_URL}
        - REPOSITORY_URI=${REPOSITORY_URI}
        - SERVER_SONAR=${SERVER_SONAR}
        - ACCESS_TOKEN_SONAR=${ACCESS_TOKEN_SONAR}
    environment:
      - SERVER_SONAR=${SERVER_SONAR}
      - ACCESS_TOKEN_SONAR=${ACCESS_TOKEN_SONAR}
volumes:
  node_modules:
