version: '3.8'

services:
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: local
      context: .
      args:
        - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    environment:
      - TZ=${TZ}
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules/
        node_modules:/project/node_modules/

volumes:
  node_modules:
