#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# The reason we're exporting this variable is because of this issue:
# https://github.com/typicode/husky/issues/968
export FORCE_COLOR=1

npx commitlint --edit $1 ||
(
  echo '✍📤 Al parecer el formato del commit no sigue la conveción. También puede tratar de commitear con el comando "npm run commit".';
  false;
)