#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# The reason we're exporting this variable is because of this issue:
# https://github.com/typicode/husky/issues/968
export FORCE_COLOR=1

echo '🔍🎨 Formatear y verificar antes del commit!'

npx lint-staged ||
(
  echo '💀❌ Ooops! El proceso de formateado ha fallado!';
  false;
)

echo '🥳✅ El proceso de formateo y verificación se ha completado con éxito!'